### PR TITLE
Add a help command

### PR DESCRIPTION
**Pull request by RobertAudi**
Add a help command along with help files. Usage:

``` bash
$ np help
$ np help add
$ np help help
```

### CODE REVIEW

**Comment by joelpurra** [comment]
@RobertAudi: that's a great addition! Nice to see that it's easily extensible as well.

Thank you very much =)

**Comment by joelpurra** [comment]
Released v1.2.0 with the `np help` command.

**Comment by RobertAudi** [comment]
@joelpurra You are welcome :+1: 

I also wanted to generate a man page from the [`USAGE.md`](https://github.com/joelpurra/npshell/blob/master/USAGE.md) file and I did, but I used [md2man](https://github.com/sunaku/md2man) which is a ruby gem. 

It might be better to use something like [groff](https://www.gnu.org/software/groff) (which comes with OS X and probably some Linux distros) and automate the generation with a Makefile. But that would mean that the help/manpage will need to be writter in a format supported by groff...

Unless you don't mind having a ruby gem as development dependency.

**Comment by joelpurra** [comment]
@RobertAudi: It'd be sweet to have a man page! Can you add it?

Ruby with md2man isn't a trivial dependency as I'm not sure which platforms people use `np` on, but guess developers could check in the generated roff file after each `USAGE.md` change. (Checking in generated files isn't something I like to do or encourage though.)

I'm using `brew install npshell`, and there's [support for installing man pages with brew](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook). If you are a brew user it'd be great to see the new man page built and installed by [`npshell.rb`](https://github.com/joelpurra/homebrew-joelpurra/blob/master/npshell.rb).

By the way -- brew is written in ruby and also knows about ruby gems, so maybe it's a trivial dependency for brew?

**Comment by RobertAudi** [comment]
I am a homebrew user but I am not sure about recipes creation. However I just got an idea. We could generate a manpage using a pre-commit git hook and commit the thing. I don't see what's wrong with committing it even if it's generated since it's not specific to the environment of a user. Also, as I said before, I don't think a set of development dependencies would be a problem. Regular users won't need them.

**Comment by joelpurra** [comment]
@RobertAudi: sure, that'd be convenient -- if the pre-commit hook doesn't crash for developers who don't have all dependencies. If they changed `USAGE.md` there could be a warning though.

**Comment by RobertAudi** [comment]
@joelpurra The pre-commit hook is just a shell script. So we can check if all the deps are present.

**Comment by joelpurra** [comment]
@RobertAudi: see #4!

**Pull request merged**
